version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      validated:
        patterns:
          - nonempty-collections
          - validated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
